// Generated by CoffeeScript 1.4.0
var app, cli, express, twilioAPI;

express = require("express");

app = express();

twilioAPI = require("twilio-api");

cli = new twilioAPI.Client('ACf39e1b04d08f9909f36742fa6eacefbc', 'd95dbd5ac2495abcb055783cede32837');

app.use(cli.middleware());

app.listen(1337);

cli.account.getApplication('APfcc463968ea11abfbcf4756dbdfc563b', function(err, app) {
  if (err) {
    throw err;
  }
  app.register();
  return app.on("incomingSMSMessage", function(sms) {
    return console.log(sms.Body);
  });
});
